---
volumes:
  pgdata:

name: whatitdoo-dev
services:
  worker:
    container_name: wid-worker
    image: registry.gitlab.pycrs.cz/tul/what-it-doo/server:0.4.0
    command: worker 
    environment:
      - WID_DATABASE_HOST=database
      - WID_DATABASE_USER=postgres
      - WID_DATABASE_PASSWORD=postgres
      - WID_DATABASE_NAME=whatitdoo
      - WID_REDIS_HOST=redis
      - WID_EXTERNAL_URL=http://localhost:8080
    depends_on:
      - database
      - redis

  redis:
    container_name: wid-redis
    image: redis:8
    ports:
      - "6379:6379"

  database:
    container_name: wid-database
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data