---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: what-it-doo
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      # initContainers:
      #   - name: wait-for-migrations
      #     image: ghcr.io/groundnuty/k8s-wait-for:1.6
      #     args:
      #       - "job"
      #       - "database-migrations"

      containers:
      - name: server
        image: registry.gitlab.pycrs.cz/tul/what-it-doo/server:0.4.0
        args:
          - server
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/whatitdoo/wid.yaml
            name: config-volume
            subPath: wid.yamldocker 
        env:
          - name: WID_EXTERNAL_URL
            value: "https://wid.pycrs.cz"
        envFrom:
          - secretRef:
              name: wid-secrets
        ports:
        - containerPort: 8080
      volumes:
        - name: config-volume
          configMap:
            name: wid-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: what-it-doo
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: registry.gitlab.pycrs.cz/tul/what-it-doo/server:0.4.0
        args:
          - worker
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/whatitdoo/wid.yaml
            name: config-volume
            subPath: wid.yamldocker 
        env:
          - name: WID_EXTERNAL_URL
            value: "https://wid.pycrs.cz"
        envFrom:
          - secretRef:
              name: wid-secrets
      volumes:
        - name: config-volume
          configMap:
            name: wid-config